// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegionScope.Data;

#nullable disable

namespace RegionScope.Migrations
{
    [DbContext(typeof(RegionScopeDbContext))]
    [Migration("20261004153504_AddIndicatorsAndObservations")]
    partial class AddIndicatorsAndObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegionScope.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsEuropeanUnionMember")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AT",
                            IsEuropeanUnionMember = true,
                            Name = "Austria"
                        },
                        new
                        {
                            Code = "BE",
                            IsEuropeanUnionMember = true,
                            Name = "Belgium"
                        },
                        new
                        {
                            Code = "BG",
                            IsEuropeanUnionMember = true,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Code = "HR",
                            IsEuropeanUnionMember = true,
                            Name = "Croatia"
                        },
                        new
                        {
                            Code = "CY",
                            IsEuropeanUnionMember = true,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Code = "CZ",
                            IsEuropeanUnionMember = true,
                            Name = "Czechia"
                        },
                        new
                        {
                            Code = "DK",
                            IsEuropeanUnionMember = true,
                            Name = "Denmark"
                        },
                        new
                        {
                            Code = "EE",
                            IsEuropeanUnionMember = true,
                            Name = "Estonia"
                        },
                        new
                        {
                            Code = "FI",
                            IsEuropeanUnionMember = true,
                            Name = "Finland"
                        },
                        new
                        {
                            Code = "FR",
                            IsEuropeanUnionMember = true,
                            Name = "France"
                        },
                        new
                        {
                            Code = "DE",
                            IsEuropeanUnionMember = true,
                            Name = "Germany"
                        },
                        new
                        {
                            Code = "GR",
                            IsEuropeanUnionMember = true,
                            Name = "Greece"
                        },
                        new
                        {
                            Code = "HU",
                            IsEuropeanUnionMember = true,
                            Name = "Hungary"
                        },
                        new
                        {
                            Code = "IE",
                            IsEuropeanUnionMember = true,
                            Name = "Ireland"
                        },
                        new
                        {
                            Code = "IT",
                            IsEuropeanUnionMember = true,
                            Name = "Italy"
                        },
                        new
                        {
                            Code = "LV",
                            IsEuropeanUnionMember = true,
                            Name = "Latvia"
                        },
                        new
                        {
                            Code = "LT",
                            IsEuropeanUnionMember = true,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Code = "LU",
                            IsEuropeanUnionMember = true,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Code = "MT",
                            IsEuropeanUnionMember = true,
                            Name = "Malta"
                        },
                        new
                        {
                            Code = "NL",
                            IsEuropeanUnionMember = true,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Code = "PL",
                            IsEuropeanUnionMember = true,
                            Name = "Poland"
                        },
                        new
                        {
                            Code = "PT",
                            IsEuropeanUnionMember = true,
                            Name = "Portugal"
                        },
                        new
                        {
                            Code = "RO",
                            IsEuropeanUnionMember = true,
                            Name = "Romania"
                        },
                        new
                        {
                            Code = "SK",
                            IsEuropeanUnionMember = true,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Code = "SI",
                            IsEuropeanUnionMember = true,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Code = "ES",
                            IsEuropeanUnionMember = true,
                            Name = "Spain"
                        },
                        new
                        {
                            Code = "SE",
                            IsEuropeanUnionMember = true,
                            Name = "Sweden"
                        });
                });

            modelBuilder.Entity("RegionScope.Models.Indicator", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            Code = "population",
                            Name = "Population",
                            Unit = "persons"
                        },
                        new
                        {
                            Code = "gdp_per_capita",
                            Name = "GDP per capita",
                            Unit = "EUR per person"
                        },
                        new
                        {
                            Code = "unemployment_rate",
                            Name = "Unemployment rate",
                            Unit = "percentage"
                        });
                });

            modelBuilder.Entity("RegionScope.Models.Observation", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("IndicatorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.HasKey("CountryCode", "IndicatorCode", "Year");

                    b.HasIndex("IndicatorCode", "Year");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("RegionScope.Models.Observation", b =>
                {
                    b.HasOne("RegionScope.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegionScope.Models.Indicator", "Indicator")
                        .WithMany("Observations")
                        .HasForeignKey("IndicatorCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("RegionScope.Models.Indicator", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
